<#
    setup_mirrors.ps1 — 探测国内依赖镜像并配置全局 pip / uv / npm 镜像

    用途：国内网络直连 PyPI/npm 官方源可能极慢。本脚本先探测国内镜像可用性，
    可用则自动写入机器级全局配置；全部不可用则保持官方源不变。

    用法：powershell -ExecutionPolicy Bypass -File scripts\setup_mirrors.ps1

    幂等：重复运行会覆盖镜像配置，旧配置自动备份为 .bak-<时间戳> 文件。
    配置位置：
      - pip: %APPDATA%\pip\pip.ini
      - uv:  %APPDATA%\uv\uv.toml
      - npm: 用户级 .npmrc（registry = npmmirror）
#>
$ErrorActionPreference = "Stop"

$pyMirrors = [ordered]@{
    "TUNA"    = "https://pypi.tuna.tsinghua.edu.cn/simple"
    "Aliyun"  = "https://mirrors.aliyun.com/pypi/simple"
    "USTC"    = "https://pypi.mirrors.ustc.edu.cn/simple"
    "Tencent" = "https://mirrors.cloud.tencent.com/pypi/simple"
}
$npmMirror = "https://registry.npmmirror.com"

function Test-Mirror([string]$name, [string]$url) {
    try {
        $probe = "$($url.TrimEnd('/'))/pip/"
        $r = Invoke-WebRequest -Uri $probe -Method Get -TimeoutSec 6 -UseBasicParsing
        Write-Host "  [OK]   $name"
        return $true
    } catch {
        Write-Host "  [FAIL] $name"
        return $false
    }
}

function Test-NpmMirror([string]$url) {
    try {
        $r = Invoke-WebRequest -Uri $url -Method Get -TimeoutSec 6 -UseBasicParsing
        Write-Host "  [OK]   npmmirror"
        return $true
    } catch {
        Write-Host "  [FAIL] npmmirror"
        return $false
    }
}

function Write-Utf8NoBom([string]$path, [string]$content) {
    # pip/uv 的配置文件若带 UTF-8 BOM 会导致解析失败，必须用无 BOM 编码写入
    $utf8 = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($path, $content, $utf8)
}

function Backup-File([string]$path) {
    if (Test-Path $path) {
        $bak = "$path.bak-$((Get-Date).ToString('yyyyMMddHHmmss'))"
        Copy-Item $path $bak -Force
        Write-Host "  备份旧配置: $bak"
    }
}

Write-Host "=== 探测 PyPI 国内镜像 ==="
$selected = $null
foreach ($name in $pyMirrors.Keys) {
    if (Test-Mirror $name $pyMirrors[$name]) {
        $selected = $pyMirrors[$name]
        break
    }
}

if (-not $selected) {
    Write-Host "未找到可用的国内 PyPI 镜像，跳过 pip/uv 配置（保持官方源）。"
} else {
    Write-Host ""
    Write-Host "=== 使用镜像: $selected ==="

    $pipDir = Join-Path $env:APPDATA "pip"
    $pipIni = Join-Path $pipDir "pip.ini"
    New-Item -ItemType Directory -Force -Path $pipDir | Out-Null
    Backup-File $pipIni
    Write-Utf8NoBom $pipIni "[global]`r`nindex-url = $selected`r`ntimeout = 60`r`n"

    $uvDir = Join-Path $env:APPDATA "uv"
    $uvToml = Join-Path $uvDir "uv.toml"
    New-Item -ItemType Directory -Force -Path $uvDir | Out-Null
    Backup-File $uvToml
    Write-Utf8NoBom $uvToml "# Global dependency mirror (generated by scripts/setup_mirrors.ps1)`r`n[pip]`r`nindex-url = `"$selected`"`r`n"

    Write-Host "  pip -> $pipIni"
    Write-Host "  uv  -> $uvToml"
}

Write-Host ""
Write-Host "=== 探测 npm 国内镜像 ==="
if (Test-NpmMirror $npmMirror) {
    npm config set registry $npmMirror | Out-Null
    Write-Host "  npm registry -> $npmMirror"
} else {
    Write-Host "npmmirror 不可用，npm 保持默认官方源。"
}

Write-Host ""
Write-Host "完成。"
